---
- name: Converge
  hosts: all
  become: true

  vars:
    haproxy_socket: ''
    haproxy_chroot: ''
    haproxy_user: root
    haproxy_group: root

    haproxy_frontends:
      - name: nginx_host
        address: nginx.loc
        backend: nginx_backend

    haproxy_backend_servers:
      - name: nginx_backend
        servers:
          - name: nginx_backend_1
            address: 127.0.0.1:8080
            options: 'check fall 3 rise 2'

    haproxy_default_backend_name: nginx_backend

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: evolic.haproxy
